server:
  port: 0

spring:
  application:
    name: item-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/item_service
    username: root
    password: nayoung1234